"""empty message

Revision ID: 46088fa85257
Revises: 6262d94522b7
Create Date: 2021-03-02 22:17:13.761629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46088fa85257'
down_revision = '6262d94522b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
